# Name:		Natasha Sarkar
# Email: 	nat41575@gmail.com
# ID:    	904743795

default: 
	gcc -o lab0 -g -Wall -Wextra lab0.c

check:
	./checkscript.sh

clean:
	rm -f lab0 lab0-904743795.tar.gz

dist:
	 tar -cvzf lab0-904743795.tar.gz lab0.c README Makefile \
	 	 backtrace.png breakpoint.png checkscript.sh file1