#NAME: Natasha Sarkar
#EMAIL: nat41575@gmail.com
#ID: 904743795

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c

dist:
	tar -czvf lab3a-904743795.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a lab3a-904743795.tar.gz 