# NAME: Natasha Sarkar
# EMAIL: nat41575@gmail.com
# ID: 904743795

default: 
	rm -f lab3b
	ln my_lab3b lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-904743795.tar.gz lab3b

dist:
	tar -czvf lab3b-904743795.tar.gz lab3b.py README Makefile my_lab3b