# NAME: Natasha Sarkar
# EMAIL: nat41575@gmail.com
# ID: 904743795

default:
	gcc -o lab1a -g -Wall -Wextra lab1a.c

clean:
	rm -f lab1a lab1a-904743795.tar.gz

dist:
	tar -cvzf lab1a-904743795.tar.gz lab1a.c README Makefile